apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "usertap"
  labels:
    {{- include "usertap.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/usertap"
  type: "Opaque"
