apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "opensearch-cluster"
  labels:
    {{- include "opensearch-cluster.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/opensearch-cluster"
  type: Opaque
