prompt-keda:
  image:
    pullPolicy: Always  # TODO.  Change to IfNotPresent for load testing.
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  instrument:
    pipelines:
      # IMPORTANT: don't use flow-style mappings (i.e., {}) in pipelines specs
      # if the result (including any comments) is longer than 72 characters.
      # The config will get corrupted after template substitution.
      # Block-style mappings can have lines of any length.
      main: |-
        - survey: SURVEY
          pipelines:
          - ${PROMPT_PROCESSING_DIR}/pipelines/LSSTCam-imSim/ApPipe.yaml
          - ${PROMPT_PROCESSING_DIR}/pipelines/LSSTCam-imSim/SingleFrame.yaml
          - ${PROMPT_PROCESSING_DIR}/pipelines/LSSTCam-imSim/Isr.yaml
      preprocessing: |-
        - survey: SURVEY
          pipelines: ['${PROMPT_PROCESSING_DIR}/pipelines/LSSTCam-imSim/Preprocessing.yaml']
    calibRepo: s3://repo-test-users/or5
    skymap: "lsst_cells_v1"

  s3:
    imageBucket: repo-test
    endpointUrl: https://sdfembs3.sdf.slac.stanford.edu
    # Do not set AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID. Use cred file
    cred_file_auth: True
    auth_env: False
    aws_profile: embargo

  imageNotifications:
    kafkaClusterAddress: prompt-processing2-kafka-bootstrap.kafka:9092
    topic: or5-ppdev-notification

  apdb:
    config: s3://rubin-summit-users/apdb_config/cassandra/pp_apdb_lsstcamimsim-dev.yaml

  alerts:
    username: kafka-admin
    server: usdf-alert-stream-dev.lsst.cloud:9094
    topic: alerts-simulated

  sasquatch:
    endpointUrl: https://usdf-rsp-dev.slac.stanford.edu/sasquatch-rest-proxy
    auth_env: false

  keda:
    maxReplicaCount: 100 # TODO.  Increase after testing.

  podAnnotations: {
    edu.stanford.slac.sdf.project/usdf-embargo: "true"
  }
