apiVersion: v2
description: VictoriaMetrics Kubernetes metrics config
name: victoria-metrics-k8s
type: application
version: 1.0.0

dependencies:
  - name: victoria-metrics-k8s-stack
    version: 0.45.0
    repository: https://victoriametrics.github.io/helm-charts/
