apiVersion: v2
appVersion: "0.1.0"
description: SQL and TAP database of Rubin catalog products, with its own ClickHouse server
name: river-next
sources:
  - https://github.com/mjuric/mppdb
type: application
version: 1.0.0
