apiVersion: v2
name: obsforgetap
version: 1.0.0
description: ObsForge TAP service
sources:
  - https://github.com/lsst-sqre/tap-postgres
  - https://github.com/opencadc/tap

dependencies:
  - name: cadc-tap
    version: 1.0.0
    repository: "file://../../charts/cadc-tap"
