{{- if .Values.config.metrics.enabled -}}
apiVersion: access.strimzi.io/v1alpha1
kind: KafkaAccess
metadata:
  name: "datalinker-kafka"
  labels:
    {{- include "datalinker.labels" . | nindent 4 }}
spec:
  kafka:
    name: "sasquatch"
    namespace: "sasquatch"
    listener: "tls"
  user:
    kind: "KafkaUser"
    apiGroup: "kafka.strimzi.io"
    name: "app-metrics-datalinker"
    namespace: "sasquatch"
{{- end }}
