{{- if .Values.collab.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "collab-configmap"
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.collab.config | nindent 4 }}
  exclude-groups.yaml: |-
    {{- toYaml .Values.collab.exclude | nindent 4 }}
{{- end }}
