apiVersion: v1
kind: ConfigMap
metadata:
  name: cadc-tap-config
  labels:
    {{- include "cadc-tap.labels" . | nindent 4 }}
data:
  cadc-registry.properties: |
    ivo://ivoa.net/sso#OpenID = {{ .Values.global.baseUrl }}
    # Ignore this, it's only here to satisfy the availability check.
    ivo://ivoa.net/std/CDP#proxy-1.0 = ivo://cadc.nrc.ca/cred
    ivo://ivoa.net/sso#tls-with-password = {{ .Values.global.baseUrl }}
  catalina.properties: |
    # tomcat properties
    tomcat.connector.connectionTimeout=20000
    tomcat.connector.keepAliveTimeout=120000
    tomcat.connector.secure=false
    tomcat.connector.scheme=http
    tomcat.connector.proxyName={{ .Values.global.host }}
    tomcat.connector.proxyPort=80

    # authentication provider
    ca.nrc.cadc.auth.IdentityManager=org.opencadc.auth.StandardIdentityManager
  tap-config.properties: |
    # URL rewrite configuration
    url.rewrite.enabled={{ .Values.config.urlRewrite.enabled | default true }}
    # Format: table1:column1,table2:column2,table3:column3
    url.rewrite.rules={{ .Values.config.urlRewrite.rules | default "ivoa.ObsCore:access_url" }}
  PluginFactory.properties: |
    ca.nrc.cadc.tap.TapQuery.langValues = ADQL ADQL-2.0
    {{- if eq .Values.config.backend "bigquery" }}
    ADQL = org.opencadc.tap.dialect.bigquery.BigQueryAdqlQueryImpl
    ADQL-2.0 = org.opencadc.tap.dialect.bigquery.BigQueryAdqlQueryImpl
    ca.nrc.cadc.tap.writer.format.FormatFactory=org.opencadc.tap.dialect.bigquery.writer.format.BigQueryFormatFactory
    {{- else }}
    ADQL = org.opencadc.tap.dialect.qserv.QServAdqlQueryImpl
    ADQL-2.0 = org.opencadc.tap.dialect.qserv.QServAdqlQueryImpl
    ca.nrc.cadc.tap.writer.format.FormatFactory = org.opencadc.tap.impl.RubinFormatFactory
    {{- end }}
    ca.nrc.cadc.tap.TableWriter = org.opencadc.tap.impl.RubinTableWriter
    ca.nrc.cadc.tap.upload.datatype.DatabaseDataType = ca.nrc.cadc.tap.upload.datatype.OracleDataType
    ca.nrc.cadc.tap.ResultStore = org.opencadc.tap.impl.ResultStoreImpl
    ca.nrc.cadc.tap.schema.TapSchemaDAO = org.opencadc.tap.schema.ALMATapSchemaDAO
    ca.nrc.cadc.tap.UploadManager = org.opencadc.tap.impl.RubinUploadManagerImpl
    ca.nrc.cadc.tap.MaxRecValidator = org.opencadc.tap.impl.MaxRecValidatorImpl
