apiVersion: v2
name: semaphore
type: application
version: 1.0.0
maintainers:
  - name: jonathansick
    url: https://github.com/jonathansick
description: >-
  User notification and messaging service for the Rubin Science Platform.
sources:
  - https://github.com/lsst-sqre/semaphore
appVersion: 1.0.0

annotations:
  phalanx.lsst.io/docs: |
    - id: "SQR-060"
      title: "Design of the Semaphore user broadcast message system for the Rubin Science Platform"
      url: "https://sqr-060.lsst.io/"
