config:
  enableGithubApp: true
  githubAppId: "131502"
  slackAlerts: true
  updateSchema: true
cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-stable-6994:us-central1:science-platform-stable-0c29612b"
  serviceAccount: "semaphore@science-platform-stable-6994.iam.gserviceaccount.com"
