# Default values for semaphore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of Semaphore pods to run
replicaCount: 1

image:
  # -- Semaphore image repository
  repository: "ghcr.io/lsst-sqre/semaphore"

  # -- Image pull policy
  pullPolicy: "IfNotPresent"

  # -- Tag of the image
  # @default -- The appVersion of the chart
  tag: null

config:
  # -- URL for the PostgreSQL database if Cloud SQL is not in use
  # @default -- None, must be set if `cloudsql.enabled` is false
  databaseUrl: null

  # -- Toggle to enable the GitHub App functionality
  enableGithubApp: false

  # -- GitHub application ID
  githubAppId: null

  # -- Logging level
  logLevel: "INFO"

  # -- Logging profile (`production` for JSON, `development` for
  # human-friendly)
  logProfile: "production"

  # -- URL path prefix
  pathPrefix: "/semaphore"

  sentry:
    # -- Set to true to enable the Sentry integration.
    enabled: false

    # -- The percentage of requests that should be traced. This
    # should be a float between 0 and 1
    tracesSampleRate: 0.0

  # -- Whether to send Slack alerts for unexpected failures
  slackAlerts: false

  # -- Whether to automatically update the Semaphore database schema
  updateSchema: false

ingress:
  # -- Additional annotations to add to the ingress
  annotations: {}

# -- Affinity rules for the Semaphore pod
affinity: {}

# -- Node selection rules for the Semaphore pod
nodeSelector: {}

# -- Annotations for the Semaphore pod
podAnnotations: {}

# -- Resource requests and limits for Semaphore
# @default -- See `values.yaml`
resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "2m"
    memory: "75Mi"

# -- Tolerations for the Semaphore pod
# @default -- TolerateGKE amd64 and arm64 taints
tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "amd64"
    effect: "NoSchedule"
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"

cloudsql:
  # -- Enable the Cloud SQL Auth Proxy sidecar, used with Cloud SQL databases
  # on Google Cloud
  enabled: false

  image:
    # -- Cloud SQL Auth Proxy image to use
    repository: "gcr.io/cloudsql-docker/gce-proxy"

    # -- Cloud SQL Auth Proxy tag to use
    tag: "1.38.0"

    # -- Pull policy for Cloud SQL Auth Proxy images
    pullPolicy: "IfNotPresent"

  # -- Instance connection name for a Cloud SQL PostgreSQL instance
  # @default -- None, must be set if Cloud SQL is used
  instanceConnectionName: null

  # -- The Google service account that has an IAM binding to the `semaphore`
  # Kubernetes service account and has the `cloudsql.client` role
  # @default -- None, must be set if Cloud SQL Auth Proxy is enabled
  serviceAccount: ""

  # -- Resource limits and requests for the Cloud SQL Proxy container
  # @default -- See `values.yaml`
  resources:
    limits:
      cpu: "1"
      memory: "30Mi"
    requests:
      cpu: "5m"
      memory: "15Mi"

# Global parameters will be set by parameters injected by Argo CD and should
# not be set in the individual environment values files.
global:
  # -- Name of the Phalanx environment
  # @default -- Set by Argo CD
  environmentName: null

  # -- Host name for ingress
  # @default -- Set by Argo CD Application
  host: null

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD Application
  vaultSecretsPathPrefix: null
