image:
  tag: "t-DM-55229"
  pullPolicy: "Always"
config:
  enableGithubApp: true
  githubAppId: "131457"
  slackAlerts: true
  updateSchema: true
cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-int-dc5d:us-central1:science-platform-int-8f439af2"
  serviceAccount: "semaphore@science-platform-int-dc5d.iam.gserviceaccount.com"
