# Default values for semaphore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of Semaphore pods to run
replicaCount: 1

image:
  # -- Semaphore image repository
  repository: ghcr.io/lsst-sqre/semaphore

  # -- Image pull policy
  pullPolicy: IfNotPresent

  # -- Tag of the image
  # @default -- The appVersion of the chart
  tag: null

config:
  # -- Toggle to enable the GitHub App functionality
  enableGithubApp: false

  # -- GitHub application ID
  githubAppId: null

  # -- Logging level
  logLevel: "INFO"

  # -- Logging profile (`production` for JSON, `development` for
  # human-friendly)
  logProfile: "production"

  # -- URL path prefix
  pathPrefix: "/semaphore"

  # -- Name of the Phalanx environment where the application is installed
  # @default -- Must be set
  phalanxEnv: null

  # -- Whether to send Slack alerts for unexpected failures
  slackAlerts: false

ingress:
  # -- Additional annotations to add to the ingress
  annotations: {}

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: false

  # -- Annotations to add to the service account
  annotations: {}

  # The name of the service account to use.
  # @default -- Generated using the fullname template
  name: ""

# -- Annotations for pods
podAnnotations: {}

# -- Resource requests and limits for Semaphore
# @default -- See `values.yaml`
resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "2m"
    memory: "75Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Global parameters will be set by parameters injected by Argo CD and should
# not be set in the individual environment values files.
global:
  # -- Host name for ingress
  # @default -- Set by Argo CD Application
  host: null

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD Application
  vaultSecretsPathPrefix: null
