vm:
  spec:
    storage:
      storageClassName: "standard-rwo"

vmAgent:
  spec:
    statefulStorage:
      volumeClaimTemplate:
        spec:
          storageClassName: "standard-rwo"

vmAlertmanager:
  spec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "standard-rwo"

