{{- if .Values.config.slackAlerts }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "conesearch"
  labels:
    {{- include "conesearch.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/conesearch"
  type: Opaque
{{- end }}
