apiVersion: v1
kind: ConfigMap
metadata:
  name: "obsforge"
  labels:
    {{- include "obsforge.labels" . | nindent 4 }}
data:
  OBSFORGE_ALEMBIC_CONFIG_PATH: "/app/alembic.ini"
  OBSFORGE_ARQ_MODE: {{ .Values.config.arqMode | quote }}
  OBSFORGE_ARQ_QUEUE_NAME: {{ .Values.config.arqQueueName | quote }}
  OBSFORGE_ARQ_QUEUE_URL: "redis://obsforge-redis.{{ .Release.Namespace }}:6379/0"
  OBSFORGE_BUTLER_LABEL: {{ .Values.config.butlerLabel | quote }}
  OBSFORGE_BUTLER_REPOSITORY: {{ .Values.config.butlerRepository | quote }}
  OBSFORGE_DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  OBSFORGE_ENRICHMENT_MAX_TRIES: {{ .Values.config.enrichmentMaxTries | quote }}
  {{- if .Values.streamWorkers.enabled }}
  OBSFORGE_KAFKA_BROKER_ADDRESS: {{ required "config.kafkaBrokerAddress must be set when stream workers are enabled" .Values.config.kafkaBrokerAddress | quote }}
  OBSFORGE_KAFKA_SECURITY_PROTOCOL: {{ .Values.config.kafkaSecurityProtocol | quote }}
  OBSFORGE_KAFKA_USERNAME: {{ required "config.kafkaUsername must be set when stream workers are enabled" .Values.config.kafkaUsername | quote }}
  {{- end }}
  OBSFORGE_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  OBSFORGE_LOG_PROFILE: {{ .Values.config.logProfile | quote }}
  OBSFORGE_OBSCORE_CONFIG: {{ .Values.config.obscoreConfig | quote }}
  OBSFORGE_OBSCORE_DATASET_TYPE: {{ .Values.config.obscoreDatasetType | quote }}
  OBSFORGE_PATH_PREFIX: {{ .Values.config.pathPrefix | quote }}
  {{- if .Values.streamWorkers.enabled }}
  OBSFORGE_SCHEMA_REGISTRY_URL: {{ required "config.schemaRegistryUrl must be set when stream workers are enabled" .Values.config.schemaRegistryUrl | quote }}
  {{- end }}
  REPERTOIRE_BASE_URL: {{ .Values.global.repertoireUrl | quote }}
