cadc-tap:
  resources:
    requests:
      cpu: "1.0"
      memory: "2Gi"
    limits:
      cpu: "4.0"
      memory: "8Gi"

  config:
    jvmMaxHeapSize: 7G

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-int-dc5d:us-central1:science-platform-int-8f439af2"
    serviceAccount: "ssotap@science-platform-int-dc5d.iam.gserviceaccount.com"
    database: "ssotap"
