cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfdev-sso"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-demo-9e05:us-central1:science-platform-demo-a4dbbf96"
    serviceAccount: "ssotap@science-platform-demo-9e05.iam.gserviceaccount.com"
    database: "ssotap"
