cadc-tap:
  tapSchema:
    type: "external"
    database: "ssotap"
    username: "tap_schema_ssotap"
    useVaultPassword: true
    external:
      host: "rsp-db-ro.postgres-db"

  uws:
    type: "external"
    database: "ssotap"
    username: "uws_ssotap"
    useVaultPassword: true
    external:
      host: "rsp-db-rw.postgres-db"
