cadc-tap:
  config:
    gcsBucket: "https://async-results.lsst.codes"
    gcsBucketUrl: "https://tap-files.lsst.codes"
    datalinkPayloadUrl: "https://github.com/lsst/sdm_schemas/releases/download/DP1-v1.1.4-rc1/datalink-snippets.zip"

  pg:
    image:
      pullPolicy: Always
      tag: "tickets-DM-52819"

  nodeSelector:
    node_pool: "arm-core-pool"

  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfdev-sso"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-demo-9e05:us-central1:science-platform-demo-a4dbbf96"
    serviceAccount: "ssotap@science-platform-demo-9e05.iam.gserviceaccount.com"
    database: "ssotap"
