config:

  # -- Logging profile (`production` for JSON, `development` for
  # human-friendly)
  logProfile: "production"

  # -- APDB config file resource
  apdbConfig: "s3://embargo@rubin-summit-users/apdb_config/cassandra/pp_apdb_lsstcam.yaml"

  # -- CloudSQL Python Connector configuration
  cloudSql:

    # -- CloudSQL Connection Name
    connectionName: "ppdb-int-6c62:us-central1:ppdb-int"

    # -- Username in sa_name@project.iam format
    user: "usdf-replication@ppdb-int-6c62.iam"

  # -- PPDB config file resource
  ppdbConfig: "gs://ppdb-int-config/ppdb-int_config.yaml"

  # -- Artificially throttle chunk uploads to every 8 minutes to avoid hitting
  # -- BigQuery rate limits when testing. This is not a production setting.
  uploadInterval: 480

  # -- Volumes specific to the environment
  volumes:
    - name: sdf-group-rubin
      persistentVolumeClaim:
        claimName: sdf-group-rubin
    - name: sdf-data-rubin
      persistentVolumeClaim:
        claimName: sdf-data-rubin
    - name: sdf-scratch
      persistentVolumeClaim:
        claimName: sdf-scratch
  # -- Volume mounts
  volumeMounts:
    - name: sdf-group-rubin
      mountPath: /sdf/group/rubin
    - name: sdf-data-rubin
      mountPath: /sdf/data/rubin
    - name: sdf-scratch
      mountPath: /sdf/scratch
  # -- Persistent volume claims
  persistentVolumeClaims:
    - name: sdf-group-rubin
      storageClassName: sdf-group-rubin
    - name: sdf-data-rubin
      storageClassName: sdf-data-rubin
    - name: sdf-scratch
      storageClassName: sdf-scratch
