{{- $cluster := "sasquatch" -}}
{{ range $idx, $user := $.Values.users }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: {{ $user.username | quote }}
  labels:
    strimzi.io/cluster: {{ $.Values.cluster.name }}
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: {{ $cluster | quote }}
          key: {{ $user.username }}-password
  authorization:
    type: simple
    acls:
      {{- range $idx, $topic := $user.topics }}
      - resource:
          type: topic
          name: {{ $topic | quote }}
          patternType: literal
        type: allow
        host: "*"
        operations:
        - Read
        - Describe
        - DescribeConfigs
      {{- end }}
      {{- range $idx, $group := $user.groups }}
      - resource:
          type: group
          name: {{ $group | quote }}
          patternType: prefix
        type: allow
        host: "*"
        operations:
        - All
      {{- end }}
{{- end }}
{{ range $idx, $service := $.Values.serviceAccounts }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: {{ $service.username | quote }}
  labels:
    strimzi.io/cluster: {{ $.Values.cluster.name }}
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: {{ $cluster | quote }}
          key: {{ $service.username }}-password
  authorization:
    type: simple
    acls:
      {{- $additional := .additionalTopics | default (list) -}}
      {{- $allTopics := concat .topics $additional -}}
      {{- range $idx, $topic := $allTopics }}
      - resource:
          type: topic
          name: {{ $topic | quote }}
          patternType: literal
        type: allow
        host: "*"
        operations:
        - Write
        - Describe
      {{- end }}
{{- end }}
