{{- if .Values.applications.sasquatch -}}
apiVersion: v1
kind: Namespace
metadata:
  name: "sasquatch"
  {{- if .Values.defaultComputeClass | or .Values.namespaceLabels.sasquatch }}
  labels:
  {{- if .Values.defaultComputeClass }}
    cloud.google.com/default-compute-class: {{ .Values.defaultComputeClass }}
  {{- end}}
  {{- with .Values.namespaceLabels.sasquatch }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "sasquatch"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "sasquatch"
    server: "https://kubernetes.default.svc"
  project: "monitoring"
  source:
    path: "applications/sasquatch"
    repoURL: {{ .Values.repoUrl | quote }}
    targetRevision: {{ or (index .Values "revisions" "sasquatch") .Values.targetRevision | quote }}
    helm:
      parameters:
        - name: "global.host"
          value: {{ .Values.fqdn | quote }}
        - name: "global.baseUrl"
          value: "https://{{ .Values.fqdn }}"
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vaultPathPrefix | quote }}
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.name }}.yaml"
{{- end -}}
