slack-alert-webhook:
  description: >-
    Webhook of a slack channel to configure the general Slack alert contact point with.
    https://grafana.com/docs/grafana/latest/alerting/fundamentals/notifications/contact-points/
  copy:
    application: mobu
    key: app-alert-webhook
