apiVersion: v1
kind: ConfigMap
metadata:
  name: "docverse"
  labels:
    {{- include "docverse.labels" . | nindent 4 }}
data:
  DOCVERSE_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  DOCVERSE_LOG_PROFILE: {{ .Values.config.logProfile | quote }}
  DOCVERSE_PATH_PREFIX: {{ .Values.config.pathPrefix | quote }}
  DOCVERSE_DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  DOCVERSE_ARQ_REDIS_URL: {{ .Values.config.arqRedisUrl | quote }}
  REPERTOIRE_BASE_URL: {{ .Values.global.repertoireUrl | quote }}
