apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "docverse"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "docverse.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/docverse"
  type: Opaque
