apiVersion: apps/v1
kind: Deployment
metadata:
  name: "docverse-worker"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    {{- include "docverse.labels" . | nindent 4 }}
    app.kubernetes.io/component: "worker"
    docverse-redis-client: "true"
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      {{- include "docverse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "worker"
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "docverse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "worker"
        docverse-redis-client: "true"
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.cloudsql.enabled }}
      serviceAccountName: "docverse"
      {{- else }}
      automountServiceAccountToken: false
      {{- end }}
      containers:
        - name: "docverse-worker"
          command: ["arq"]
          args: ["docverse.worker.main.WorkerSettings"]
          env:
            - name: "DOCVERSE_DATABASE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "docverse"
                  key: "DOCVERSE_DATABASE_PASSWORD"
            {{- if .Values.config.slackAlerts }}
            - name: "DOCVERSE_SLACK_WEBHOOK"
              valueFrom:
                secretKeyRef:
                  name: "docverse"
                  key: "slack-webhook"
            {{- end }}
          envFrom:
            - configMapRef:
                name: "docverse"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.workerResources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
      {{- if .Values.cloudsql.enabled }}
      initContainers:
        {{- include "docverse.cloudsqlSidecar" . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
