image:
  tag: "tickets-DM-54788"
  pullPolicy: "Always"

vaultSecretsEnabled: false

config:
  logLevel: "DEBUG"
  bigqueryProject: "ppdb-prod"
  bigqueryLocation: "US"
  gcpServiceAccount: "bigquery-kafka@science-platform-int-dc5d.iam.gserviceaccount.com"
  metrics:
    enabled: true
  sentry:
    enabled: false
  slack:
    enabled: false
  bigqueryMaxBytesBilled: 1000000000000
redis:
  persistence:
    enabled: true

