cadc-tap:
  config:
    backend: "bigquery"
    kafka:
      enabled: true
      kafkaUserName: "ppdbtap"
      consumerGroupId: "ppdbtap"
      topics:
        jobRun: "lsst.ppdbtap.job-run"
        jobStatus: "lsst.ppdbtap.job-status"
        jobDelete: "lsst.ppdbtap.job-delete"

    urlRewrite:
      enabled: true
      rules: "ivoa.ObsCore:access_url"

    bigquery:
      project: "ppdb-int-6c62"
      dataset: "ppdb_public"
      schema: "ppdb"

      tableMappings:
        - "ppdb.DiaObject:`ppdb-int-6c62.ppdb_public.DiaObject`"
        - "ppdb.DiaSource:`ppdb-int-6c62.ppdb_public.DiaSource`"
        - "ppdb.DiaForcedSource:`ppdb-int-6c62.ppdb_public.DiaForcedSource`"
        - "dp2.DiaObject:`ppdb-int-6c62.dp2.DiaObject`"
        - "dp2.DiaSource:`ppdb-int-6c62.dp2.DiaSource`"
        - "dp2.ForcedSourceOnDiaObject:`ppdb-int-6c62.dp2.ForcedSourceOnDiaObject`"
        - "dp2.SSObject:`ppdb-int-6c62.dp2.SSObject`"
        - "dp2.SSSource:`ppdb-int-6c62.dp2.SSSource`"
        - "dp2.mpc_orbits:`ppdb-int-6c62.dp2.mpc_orbits`"
        - "dp2.current_identifications:`ppdb-int-6c62.dp2.current_identifications`"
        - "dp2.numbered_identifications:`ppdb-int-6c62.dp2.numbered_identifications`"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-int-dc5d:us-central1:science-platform-int-8f439af2"
    serviceAccount: "ppdbtap@science-platform-int-dc5d.iam.gserviceaccount.com"
    database: "ppdbtap"
