# Default values for trident.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

trident-operator:
  # -- Which cloud platform is Trident running on?
  cloudProvider: "GCP"
  # -- Log format can be "json" or "text"
  tridentLogFormat: json

# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- Base URL for the environment
  # @default -- Set by Argo CD
  baseUrl: null

  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: null

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: null
