fqdn: "usdf-cm-dev.slac.stanford.edu"
name: "usdf-cm-dev"
title: "Development CM for USDF"
titleLong: "Rubin Campaign Management development at USDF"
description: >-
  The development environment for the Rubin Campaign Management service
  software at the United States Data Facility (USDF) hosted at SLAC. This
  software monitors and mediates the LSST data reduction pipelines at the
  USDF.

appOfAppsName: "science-platform"
vaultUrl: "https://vault.slac.stanford.edu"
vaultPathPrefix: "secret/rubin/usdf-cm-dev"

applications:
  # This environment uses an ingress managed in a separate Kubernetes cluster,
  # despite that configuration not being officially supported by Phalanx.
  cert-manager: false
  ingress-nginx: false

  cm-service: true
  postgres: true
