fqdn: "usdf-rsp-lsstsci.slac.stanford.edu"
name: "usdf-lsstsci"
appOfAppsName: "science-platform"
butlerServerRepositories:
  embargo: "https://usdf-rsp-lsstsci.slac.stanford.edu/api/butler/repo/embargo/butler.yaml"
vaultUrl: "https://vault.slac.stanford.edu"
vaultPathPrefix: "secret/rubin/usdf-lsstsci"

applications:
  # This environment uses an ingress managed in a separate Kubernetes cluster,
  # despite that configuration not being officially supported by Phalanx.
  ingress-nginx: false

  postgres: true
