name: "usdfint"
fqdn: "usdf-rsp-int.slac.stanford.edu"
title: "USDF RSP integration"
titleLong: "Rubin US Data Facility RSP integration"
description: >-
  The integration environment for the Rubin Science Platform at the United
  States Data Facility (USDF) hosted at SLAC. Its primary use is for Rubin
  operations teams to integrate applications into the Rubin Science Platform
  that need to run at the USDF.

appOfAppsName: "science-platform"
butlerServerRepositories:
  embargo: "https://usdf-rsp-int.slac.stanford.edu/api/butler/repo/embargo/butler.yaml"
vaultUrl: "https://vault.slac.stanford.edu"
vaultPathPrefix: "secret/rubin/usdf-rsp-int"

applications:
  # This environment uses an ingress managed in a separate Kubernetes cluster,
  # despite that configuration not being officially supported by Phalanx.
  ingress-nginx: false

  butler: true
  consdbtap: true
  consdb: true
  datalinker: true
  livetap: true
  mobu: true
  nublado: true
  plot-navigator: true
  portal: true
  ppdb-replication: true
  qserv-kafka: true
  sasquatch: true
  schedview-snapshot: true
  schedview-static-pages: true
  semaphore: true
  squareone: true
  ssotap: true
  strimzi-access-operator: true
  strimzi-registry-operator: true
  strimzi: true
  tap: true
