fqdn: "usdf-rapid-analysis.slac.stanford.edu"
name: "usdf-rapid-analysis"
title: "Rapid analysis"
titleLong: "Rapid analysis for USDF"
description: >-
  The production environment for the Rubin Rapid Analysis service software at
  the United States Data Facility (USDF) hosted at SLAC. This software does
  real-time processing of incoming data at the USDF.

appOfAppsName: "science-platform"
vaultUrl: "https://vault.slac.stanford.edu"
vaultPathPrefix: "secret/rubin/usdf-rapid-analysis"

applications:
  # This environment uses an ingress managed in a separate Kubernetes cluster,
  # despite that configuration not being officially supported by Phalanx.
  cert-manager: false
  gafaelfawr: false
  ingress-nginx: false

  rapid-analysis: true
