{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "mppdb.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "mppdb.labels" -}}
helm.sh/chart: {{ include "mppdb.chart" . }}
{{ include "mppdb.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "mppdb.selectorLabels" -}}
app.kubernetes.io/name: "mppdb"
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Public base URL the service advertises in the URLs it generates. Defaults to the
environment's base URL plus the ingress path prefix, which is what the ingress
actually serves; `config.baseUrl` overrides it when the two must differ.
*/}}
{{- define "mppdb.baseUrl" -}}
{{- if .Values.config.baseUrl -}}
{{- .Values.config.baseUrl -}}
{{- else -}}
{{- printf "%s%s" (required "global.baseUrl or config.baseUrl must be set" .Values.global.baseUrl) .Values.ingress.pathPrefix -}}
{{- end -}}
{{- end }}

{{/*
The mppdb TOML configuration file. Only the `[databases]` catalog (and the
optional `[branding]` table) live here: mppdb reads the catalog *only* from the
TOML file, while every flat scalar setting comes from the environment, where it
is easier to override per environment. `registry` paths are resolved against
`config.registryDir`, a directory baked into the image.
*/}}
{{- define "mppdb.mppdbToml" -}}
# Generated by the mppdb Helm chart. Edit applications/mppdb/values.yaml, never
# this file: it is replaced on every sync.
default_database = {{ .Values.config.defaultDatabase | quote }}
advertise_request_base = {{ .Values.config.advertiseRequestBase }}
{{- range $name, $db := .Values.config.databases }}

[databases.{{ $name }}]
ch_database = {{ required (printf "config.databases.%s.chDatabase must be set" $name) $db.chDatabase | quote }}
{{- with $db.manifestsDir }}
manifests_dir = {{ . | quote }}
{{- end }}
{{- with $db.lakeDir }}
lake_dir = {{ . | quote }}
{{- end }}
{{- with $db.registry }}
registry = {{ printf "%s/%s" (trimSuffix "/" $.Values.config.registryDir) . | quote }}
{{- end }}
{{- end }}
{{- with .Values.config.branding }}

[branding]
{{- range $key, $value := . }}
{{ $key }} = {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
