cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-usdf-dev-cdb"
      tag: "w.2026.18"

  config:
    datalinkPayloadUrl: "https://github.com/lsst/sdm_schemas/releases/download/w.2026.18/datalink-snippets.zip"
