config:
  metrics:
    enabled: true
  sentry:
    enabled: true
  slack:
    enabled: true
  qservDatabaseUrl: "mysql+asyncmy://qsmaster@134.79.23.229:4040/"
  qservRestSendApiVersion: false
  qservRestUrl: "https://134.79.23.229:4048/"
  qservRestUsername: "qsmaster"
resultWorker:
  autoscaling:
    minReplicas: 4
    maxReplicas: 50
redis:
  resources:
    limits:
      cpu: "1"
      memory: "500Mi"
    requests:
      cpu: "10m"
      memory: "200Mi"
