config:
  jobRunBatchSize: 50
  logLevel: "DEBUG"
  metrics:
    enabled: true
  sentry:
    enabled: true
  slack:
    enabled: true
  qservDatabaseUrl: "mysql+asyncmy://qsmaster@qserv-int.slac.stanford.edu:4040/"
  qservRestMaxConnections: 55
  qservRestSendApiVersion: false
  qservRestUrl: "https://qserv-int.slac.stanford.edu:4048/"
  qservRestUsername: "qsmaster"
slowWorker:
  autoscaling:
    maxReplicas: 50
redis:
  resources:
    limits:
      cpu: "1"
      memory: "200Mi"
