config:
  logLevel: "DEBUG"
  metrics:
    enabled: true
  sentry:
    enabled: true
  slack:
    enabled: true
  qservDatabaseUrl: "mysql+asyncmy://qsmaster@134.79.23.230:4040/"
  qservRestSendApiVersion: false
  qservRestUrl: "https://134.79.23.230:4048/"
  qservRestUsername: "qsmaster"
frontend:
  allowRootDebug: true
resultWorker:
  allowRootDebug: true
  autoscaling:
    maxReplicas: 50
