config:
  logLevel: "DEBUG"
  metrics:
    enabled: true
  sentry:
    enabled: true
  slack:
    enabled: true
  qservDatabaseUrl: "mysql+asyncmy://qsmaster@qserv-int.slac.stanford.edu:4040/"
  qservRestUrl: "https://qserv-int.slac.stanford.edu:4048/"
  qservRestUsername: "qsmaster"
