apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "qserv-kafka-worker"
  labels:
    {{- include "qserv-kafka.labels" . | nindent 4 }}
spec:
  podSelector:
    # This policy controls inbound and outbound access to all qserv-kafka
    # pods. Since qserv-kafka only makes outbound connections to Kafka and the
    # backend, inbound connections can be blocked for all pods.
    matchLabels:
      {{- include "qserv-kafka.selectorLabels" . | nindent 6 }}
  policyTypes:
    # Block all inbound access.
    - Ingress
