apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "ephemcache"
  labels:
    {{- include "ephemcache.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/ephemcache"
  type: Opaque
