apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "prompt-pub"
  labels:
    {{- include "prompt-pub.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/prompt-pub"
  type: Opaque
