apiVersion: v1
kind: Service
metadata:
  name: gcp-tsop-headless
spec:
  clusterIP: None
  selector:
    {{- include "gcp-tsop.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      name: http