apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "gcp-tsop"
  labels:
    {{- include "gcp-tsop.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/gcp-tsop"
  type: Opaque
