config:
  metrics:
    enabled: true
  sentryTracesSampleConfig: errors
  githubRefreshApp:
    acceptedGithubOrgs:
      - lsst-sqre
      - lsst
  githubCiApp:
    acceptedGithubOrgs:
      - lsst-sqre
      - lsst
    users:
      - username: bot-mobu-ci-user-1
      - username: bot-mobu-ci-user-2
      - username: bot-mobu-ci-user-3
      - username: bot-mobu-ci-user-4
    scopes:
      - "exec:notebook"
      - "exec:portal"
      - "read:image"
      - "read:tap"
  autostart:
    - name: "usdf-s3-speedtest"
      # Increase replicas and count (1:1) when we're ready to hammer it.
      # Each pod ought to be already about maxed out.  7 pods should fit
      # on a node.  Each node has a gVNIC that should be capable of
      # 100Gbps.  We don't know how much bandwidth we can get out of
      # USDF, but this should let us find out.
      #
      # A single Pod with 4VCPUs seems to get roughly 10Gbps, so we
      # might not be able to saturate the gVNIC with our current machine
      # size and node size type.  But maybe we'll saturate USDF's pipe
      # first.
      #
      # Any bets on whether Cyber decides we're a threat and cuts us
      # off?
      #
      # We're writing output to /rubin/shared/speedtest; eventually I'll
      # write a notebook to collect and graph that data.
      count: 100
      replicas: 100
      user_spec:
       username_prefix: "bot-mobu-usdf-speedtest"
       uid_start: 100300
       gid_start: 100300
       groups:
         - name: "g_users"
           id: 2000000
      scopes:
        - "exec:notebook"
      business:
        type: "NotebookRunnerCounting"
        options:
          repo_url: "https://github.com/lsst-sqre/usdf-speedtest-notebook.git"
          repo_ref: "main"
        restart: true
    - name: "phalanx-quotidian"
      count: 1
      users:
        - username: "bot-mobu-quotidian"
      scopes:
        - "exec:internal-tools"
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
        - "write:sasquatch"
      business:
        type: "NotebookRunnerCounting"
        options:
          image:
            image_class: "latest-daily"
          repo_url: "https://github.com/lsst-sqre/phalanx-test.git"
          repo_ref: "main"
        restart: true
    - name: "phalanx-recommended"
      count: 1
      users:
        - username: "bot-mobu-phlx-rec"
      scopes:
        - "exec:internal-tools"
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
        - "write:sasquatch"
      business:
        type: "NotebookRunnerCounting"
        options:
          repo_url: "https://github.com/lsst-sqre/phalanx-test.git"
          repo_ref: "main"
        restart: true
    - name: "tutorial"
      count: 1
      users:
        - username: "bot-mobu-tutorial"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunnerCounting"
        options:
          repo_url: "https://github.com/lsst/tutorial-notebooks.git"
          repo_ref: "main"
          max_executions: 1
        restart: true
    - name: "tutorial-adhoc"
      # Designed to let us take an arbitrary tag and see whether
      # tutorials pass on it.  Just change the tag under options.image.tag.
      count: 1
      users:
        - username: "bot-mobu-adhoc"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunnerCounting"
        options:
          image:
            image_class: "by-tag"
            tag: "r29_2_0_rsp2590"
          repo_url: "https://github.com/lsst/tutorial-notebooks.git"
          repo_ref: "main"
          max_executions: 1
        restart: true
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu-tap"
      scopes: ["read:tap"]
      business:
        type: "TAPQuerySetRunner"
        options:
          dataset: "dp02"
          query_set: "dp0.2"
          sync: false
        restart: true
    - name: "sia"
      count: 1
      users:
        - username: "bot-mobu-sia"
      scopes: ["read:image"]
      business:
        type: "SIAQuerySetRunner"
        options:
          dataset: "dp02"
          query_set: "dp02"
        restart: true
