replicaCount: 2

config:
  logMonkeysToFile: false
  metrics:
    enabled: true
  sentryTracesSampleConfig: errors
  githubRefreshApp:
    acceptedGithubOrgs:
      - lsst-sqre
  githubCiApp:
    acceptedGithubOrgs:
      - lsst-sqre
      - lsst
    users:
      - username: bot-mobu-ci-user-1
      - username: bot-mobu-ci-user-2
      - username: bot-mobu-ci-user-3
      - username: bot-mobu-ci-user-4
    scopes:
      - "exec:notebook"
      - "exec:portal"
      - "read:image"
      - "read:tap"
  autostart:
    - name: "recommended"
      count: 50
      user_spec:
        username_prefix: "bot-mobu-scale-qserv"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      # start_batch_size: 50
      # start_batch_wait: "1m"
      business:
        type: "NotebookRunnerInfinite"
        options:
          repo_url: "https://github.com/lsst-sqre/scaletest.git"
          repo_ref: "main"
          notebook_idle_time: 0
          execution_idle_time: 0
          idle_time: 0
          collection_rules:
            - type: "intersect_union_of"
              patterns:
              - "dm_v_and_v/test_LVV-T2700.ipynb"
        restart: true
