---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "gcsfuse-cache2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo
