apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "skyviewer"
  labels:
    {{- include "skyviewer.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/skyviewer"
  type: "Opaque"
