alert-brokers:
  enabled: true

  topics:
    - name: alert-stream-test
      partitions: 400
      replicas: 3
    - name: alerts-simulated
      partitions: 45
      replicas: 3
    - name: lsst-alerts-v10.0
      partitions: 45
      replicas: 3
      bytesRetained: "300000000000"
      millisecondsRetained: "2629740000"

  communityReadonlyTopics: &communityReadonlyTopics
    - "alerts-simulated"
    - "lsst-alerts-v10.0"
    - "lsst-alerts-reprocessed-v10.0"

  users:

    # A user for development purposes by the Rubin team, with access to all
    # topics in readonly mode.
    - username: "rubin-devel-idfint"
      topics:
        - "*"
      groups:
        - "rubin-devel-idfint"

    # The community broker users
    - username: "alerce-usdf"
      topics: *communityReadonlyTopics
      groups:
        - "alerce-usdf"
    - username: "ampel-usdf"
      topics: *communityReadonlyTopics
      groups:
        - "ampel-usdf"
    - username: "antares-usdf"
      topics: *communityReadonlyTopics
      groups:
        - "antares-usdf"
    - username: "babamul-usdf"
      topics: *communityReadonlyTopics
      groups:
        - "babamul-usdf"
    - username: "fink-usdf"
      topics: *communityReadonlyTopics
      groups:
        - "fink-usdf"
    - username: "lasair-usdf"
      topics: *communityReadonlyTopics
      groups:
        - "lasair-usdf"
    - username: "pittgoogle-usdf"
      topics: *communityReadonlyTopics
      groups:
        - "pittgoogle-usdf"
    - username: "poi-usdf"
      topics: *communityReadonlyTopics
      groups:
        - "poi-usdf"
    - username: "snaps-usdf"
      topics: *communityReadonlyTopics
      groups:
        - "snaps-usdf"

  serviceAccounts:

    - username: "prompt-alert"
      topics: *communityReadonlyTopics

alert-database:
  enabled: true

  ingester:
    # The image can use either a tag or a digest to determine which is being used.
    image:
      tag: v3.4.0

    logLevel: verbose

    schemaRegistryURL: http://sasquatch-schema-registry:8081

    serviceAccountName: alert-database-writer

    kafka:
      cluster: sasquatch
      topic:
        - lsst-alerts-v10.0

  ingress:
    enabled: true
    host: usdfprod-prompt-processing.slac.stanford.edu

alert-stream-schema-sync:
  enabled: true
  schemaSync:
    image:
      tag: tickets-DM-53520

chronograf:
  enabled: false

influxdb:
  enabled: false

influxdb-enterprise-standby:
  enabled: false

kafdrop:
  enabled: false
  ingress:
    enabled: false

kapacitor:
  enabled: false

schema-registry:
  enabled: true
  ingress:
    enabled: true
    anonymous: true
    hostname: rubin-alert-schemas.slac.stanford.edu
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        # Forbid everything except GET since this should be a read-only ingress
        # to the schema registry.
        limit_except GET {
          deny all;
        }

strimzi-kafka:
  cluster:
    monitorLabel:
      prometheus.io/scrape: "true"
  kafka:
    version: "4.1.0"
    replicationFactor: 3
    replicas: 5
    config:
      # -- Replica lag time can't be smaller than request.timeout.ms configuration in kafka connect.
      replica.lag.time.max.ms: 120000
      log.retention.minutes: 10080
      offsets.retention.minutes: 10080
      min.insync.replicas: 2
    listeners:
      tls:
        enabled: true
      plain:
        enabled: true
      external:
        enabled: true
    externalListener:
      tls:
        enabled: false
      bootstrap:
        host: rubin-alert-stream-bootstrap.slac.stanford.edu
        annotations:
          metallb.io/address-pool: sdf-dmz
          metallb.io/loadBalancerIPs: 134.79.23.209
        allocateLoadBalancerNodePorts: false
      brokers:
        - broker: 5
          host: rubin-alert-stream-broker-5.slac.stanford.edu
          annotations:
            metallb.io/address-pool: sdf-dmz
            metallb.io/loadBalancerIPs: 134.79.23.212
        - broker: 6
          host: rubin-alert-stream-broker-6.slac.stanford.edu
          annotations:
            metallb.io/address-pool: sdf-dmz
            metallb.io/loadBalancerIPs: 134.79.23.213
        - broker: 7
          host: rubin-alert-stream-broker-7.slac.stanford.edu
          annotations:
            metallb.io/address-pool: sdf-dmz
            metallb.io/loadBalancerIPs: 134.79.23.215
        - broker: 8
          host: rubin-alert-stream-broker-8.slac.stanford.edu
          annotations:
            metallb.io/address-pool: sdf-dmz
            metallb.io/loadBalancerIPs: 134.79.23.210
        - broker: 9
          host: rubin-alert-stream-broker-9.slac.stanford.edu
          annotations:
            metallb.io/address-pool: sdf-dmz
            metallb.io/loadBalancerIPs: 134.79.23.211
    metricsConfig:
      enabled: true
      includeTopicMetrics: true

  broker:
    enabled: true
    name: kafka
    replicas: 5
    nodeIds: "[5,6,7,8,9]"
    storage:
      size: 35Ti
      storageClassName: wekafs--sdf-k8s01
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: strimzi.io/cluster
                  operator: In
                  values:
                    - sasquatch
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 8
        memory: 32Gi
      limits:
        cpu: 8
        memory: 32Gi

  controller:
    enabled: true
    name: controller
    replicas: 5
    nodeIds: "[0,1,2,3,4]"
    storage:
      size: 100Gi
      storageClassName: wekafs--sdf-k8s01
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: strimzi.io/cluster
                  operator: In
                  values:
                    - sasquatch
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 4
        memory: 8Gi
      limits:
        cpu: 4
        memory: 8Gi

  cruiseControl:
    enabled: true

  kafkaExporter:
    enabled: true
