{{- if .Values.config.slackAlerts -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "weatherbroadcaster"
  labels:
    {{- include "weatherbroadcaster.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/weatherbroadcaster"
  type: Opaque
{{- end }}
