{{- if .Values.applications.herald -}}
apiVersion: v1
kind: Namespace
metadata:
  name: "herald"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "herald"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "herald"
    server: "https://kubernetes.default.svc"
  project: "rsp"
  source:
    path: "applications/herald"
    repoURL: {{ .Values.repoUrl | quote }}
    targetRevision: {{ or (index .Values "revisions" "herald") .Values.targetRevision | quote }}
    helm:
      parameters:
        - name: "global.host"
          value: {{ .Values.fqdn | quote }}
        - name: "global.baseUrl"
          value: "https://{{ .Values.fqdn }}"
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vaultPathPrefix | quote }}
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.name }}.yaml"
{{- end -}}
