apiVersion: v1
kind: Service
metadata:
  name: "log-explorer"
  labels:
    {{- include "log-explorer.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: "http"
      protocol: "TCP"
      name: "http"
  selector:
    {{- include "log-explorer.selectorLabels" . | nindent 4 }}
