apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "log-explorer"
  labels:
    {{- include "log-explorer.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/log-explorer"
  type: "Opaque"
