redis:
  persistence:
    size: "100Gi"

    # -- Class of storage to request
    storageClass: "wekafs--sdf-k8s01"

  resources:
    limits:
      cpu: "1"
      memory: "4Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
