"""Utilities for managing test data."""

import json
from pathlib import Path
from typing import Any
from unittest.mock import call

import yaml
from safir.testing.data import Data

from phalanx.models.secrets import StaticSecrets

__all__ = ["PhalanxData"]


class PhalanxData(Data):
    """Test data management class."""

    def assert_calls_match(self, seen: list[Any], path: str) -> None:
        """Raise an assertion if the saved expected calls don't match.

        Parameters
        ----------
        seen
            Observed data in the test to be compared. This must be a list of
            `~unittest.mock.call` objects.
        path
            Path relative to :file:`tests/data` of the expected output. A
            ``.json`` extension will be added automatically.

        Raises
        ------
        AssertionError
            Raised if the data doesn't match.
        """
        if self._update:
            self.write_calls(seen, path)
        assert seen == self.read_calls(path)

    def assert_json_dirs_match(self, seen: Path, expected: str) -> None:
        """Assert that two directories full of JSON files match.

        Parameters
        ----------
        seen
            The tree of JSON files generated by the test.
        expected
            The path, relative to the test data directory, of the expected
            output.
        """
        left_files = {p.name for p in seen.iterdir()}
        right = self.path(expected)
        right_files = {p.name for p in right.iterdir()}
        assert left_files == right_files
        for left_path in seen.iterdir():
            with left_path.open() as fh:
                left_json = json.load(fh)
            with (right / left_path.name).open() as fh:
                assert left_json == json.load(fh)

    def read_calls(self, path: str) -> list[Any]:
        """Read expected calls captured by a mock.

        Parameters
        ----------
        path
            Path relative to :file:`tests/data`. A ``.json`` extension will be
            added automatically.

        Returns
        -------
        list of call
            List of calls.
        """
        return [call(*c["args"], **c["kwargs"]) for c in self.read_json(path)]

    def read_static_secrets(self, path: str) -> StaticSecrets:
        """Read static secrets as YAML and return the parsed format.

        Parameters
        ----------
        path
            Path relative to :file:`tests/data`. A ``.yaml`` extension will be
            added automatically.

        Returns
        -------
        StaticSecrets
            Parsed version of the YAML.
        """
        secrets_path = self.path(path, "yaml")
        with secrets_path.open() as fh:
            return StaticSecrets.model_validate(yaml.safe_load(fh))

    def write_calls(self, data: list[Any], path: str) -> None:
        """Write mock calls as JSON to the test data directory.

        Parameters
        ----------
        data
            Data to write. This must be a list of `~unittest.mock.call`
            objects.
        path
            Path relative to :file:`tests/data`. A ``.json`` extension will be
            added automatically.
        """
        json_data = [{"args": c.args, "kwargs": c.kwargs} for c in data]
        self.write_json(json_data, path)
