apiVersion: v2
name: sia
version: 1.0.0
type: application
description: "Simple Image Access (SIA) IVOA Service using Butler"
sources:
  - "https://github.com/lsst-sqre/sia"
appVersion: 1.4.0

annotations:
  phalanx.lsst.io/docs: |
    - id: "SQR-095"
      title: "SIAv2 over Butler FastAPI service"
      url: "https://sqr-095.lsst.io"
