{{- if .Values.cronjob.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "reaper"
  labels:
    {{- include "reaper.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "serviceAccount must be set to a valid Google service account" .Values.serviceAccount | quote }}
{{- end }}
