image:
  pullPolicy: "Always"
  tag: "tickets-dm-48400"
config:
  registries:
   - category: "pkg.dev"
     registry: "https://us-central1-docker.pkg.dev"
     owner: "rubin-shared-services-71ec"
     namespace: "sciplat"
     repository: "sciplat-lab"
     keep:
       untagged:
         number: 4
       semver: null
       rsp:
         release:
           age: "1096d"
         weekly:
           number: 78
         daily:
           number: 25
         releaseCandidate:
           number: 5
         experimental:
           age: "30d"
         unknown:
           age: "7d"
     imageVersionClass: "rsp"
     dryRun: True
     debug: True
     skipTags:
       - "recommended"
       - "latest"
       - "latest_daily"
       - "latest_weekly"
       - "latest_release"
       - "w_2022_40"

