apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Chart.Name }}-db-alembic-migration"
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    metadata: {}
    spec:
      restartPolicy: Never
      containers:
        - name: db-alembic-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["alembic"]
          args: ["upgrade", "head"]
{{- with .Values.config.db }}
          env:
            - name: DB__URL
              value: "postgresql://{{ .username }}@{{ .hostname }}:{{ .port }}/{{ .name }}"
            - name: DB__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
{{- end }}
