apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config-worker"
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  {{- with .Values.worker.htcondor.config }}
  config: |
    {{- .contents | nindent 4 }}
  {{- end }}
  {{- with .Values.worker.butler }}
  butlerAuth: |
    - url: {{ .dbUrl }}
      username: {{ .dbUsername }}
      password: ${env:DAF_BUTLER_PASSWORD}
  {{- end }}
