apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-worker
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "worker"
  template:
    metadata:
      annotations:
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "worker"
    spec:
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: "{{ .Chart.Name }}-worker"
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: "http"
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-env
            - configMapRef:
                name: {{ .Chart.Name }}-htcondor-env
          env:
            - name: DB__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cm-service
                  key: internalDatabasePassword
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: "/output"
              name: "output-volume"
              {{- with .Values.config.outputVolume.subPath }}
              subPath: {{ . }}
              {{- end }}
            - mountPath: "/tmp"
              name: "tmp-volume"
            {{- with .Values.worker.htcondor.config }}
            - mountPath: {{ .mountPath }}
              name: "condor-config-volume"
              readOnly: true
            {{- end }}
            {{- with .Values.worker.butler }}
            - mountPath: {{ .mountPath }}
              name: "butler-auth-volume"
              readOnly: true
            {{- end }}
            {{- with .Values.worker.htcondor.fsRemoteDir }}
            - mountPath: {{ .mountPath }}
              name: "condor-remote-volume"
              {{- with .subPath }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-output
        - name: tmp-volume
          emptyDir:
            sizeLimit: 500Mi
        - name: condor-config-volume
          configMap:
            name: {{ $.Chart.Name }}-config-worker
            items:
              - key: config
                path: condor-config
        - name: condor-remote-volume
          persistentVolumeClaim:
            claimName: {{ $.Chart.Name }}-htcondor
        - name: butler-auth-volume
          configMap:
            name: {{ $.Chart.Name }}-config-worker
            items:
              - key: butlerAuth
                path: db-auth.yaml
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
