# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""

  controlSystem:
    # -- Application namespace for the control system deployment
    # @default -- Set by ArgoCD
    appNamespace: ""

    # -- Image tag for the control system deployment
    # @default -- Set by ArgoCD
    imageTag: ""

    # -- Site tag for the control system deployment
    # @default -- Set by ArgoCD
    siteTag: ""

    # -- Topic name tag for the control system deployment
    # @default -- Set by ArgoCD
    topicName: ""

    # -- Kafka broker address for the control system deployment
    # @default -- Set by ArgoCD
    kafkaBrokerAddress: ""

    # -- Kafka topic replication factor for control system topics
    # @default -- Set by ArgoCD
    kafkaTopicReplicationFactor: ""

    # -- Schema registry URL for the control system deployment
    # @default -- Set by ArgoCD
    schemaRegistryUrl: ""

    # -- S3 endpoint (LFA) for the control system deployment
    # @default -- Set by ArgoCD
    s3EndpointUrl: ""

redis:
  persistence:
    # -- Whether to persist Redis storage and thus tokens. Setting this to
    # false will use `emptyDir` and reset all tokens on every restart. Only
    # use this for a test deployment.
    enabled: false

    # -- Amount of persistent storage to request
    size: "1Gi"

    # -- Class of storage to request
    storageClass: ""

    # -- Access mode of storage to request
    accessMode: "ReadWriteOnce"

    # -- Use an existing PVC, not dynamic provisioning. If this is set, the
    # size, storageClass, and accessMode settings are ignored.
    volumeClaimName: ""

  config:
    maxMemory: "2500mb"
    maxMemoryPolicy: "allkeys-lru"


  # -- Resource limits and requests for the Redis pod
  # @default -- See `values.yaml`
  resources:
    limits:
      cpu: "1"
      memory: "3Gi"
    requests:
      cpu: "100m"
      memory: "1Gi"
