config:
  availableDatasets:
    - "dp02"
    - "dp03"
    - "dp1"
    - "dp2"
    - "prompt"
  hips:
    datasets:
      dp2:
        paths:
          - "color_gri"
          - "color_u"
          - "color_y"
    legacy:
      dataset: "dp1"
  metrics:
    enabled: true
  slackAlerts: true
  tap:
    schemaVersion: "main"
    servers:
      tap:
        enabled: true
        schemas:
          - dp2
          - dp1
          - ivoa_obscore
          - dp02_dc2
      ssotap:
        enabled: true
  useSubdomains:
    - "nublado"

  rules:
    sia:
      - type: "data"
        name: "sia"
        datasets:
          - "dp02"
          - "dp1"
          - "dp2"
        template: "https://{{base_hostname}}/api/sia/{{dataset}}"
        versions:
          sia-query-2.0:
            template: "https://{{base_hostname}}/api/sia/{{dataset}}/query"
            ivoaStandardId: "ivo://ivoa.net/std/SIA#query-2.0"
        openapi: "https://{{base_hostname}}/api/sia/openapi.json"
        ivoaRegistry:
          ivoaServiceType: "sia"
          records:
            dp1:
              ivoid: "ivo://org.rubinobs/sia/lsst-dp1"
              title: "Rubin Science Platform SIA Service (DP1)"
              created: "2026-05-20T00:00:00"
              description: >-
                Simple Image Access v2 service for Data Preview 1, providing
                image access to commissioning data from Rubin Observatory.

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-int-dc5d:us-central1:science-platform-int-8f439af2"
  serviceAccount: "repertoire@science-platform-int-dc5d.iam.gserviceaccount.com"
