config:
  rules:
    # Override the required scope of times-square. Unfortunately, there is no
    # way to do this at the moment without duplicating the entry.
    times-square:
      - type: "internal"
        name: "times-square"
        requiredScopes:
          - "exec:admin"
        template: "https://{{base_hostname}}/times-square/api"
        openapi: "https://{{base_hostname}}/times-square/api/openapi.json"
        docsUrl: "https://times-square.lsst.io/"
        versions:
          v1:
            template: "https://{{base_hostname}}/times-square/api/v1"
  slackAlerts: true
nodeSelector:
  node_pool: arm-core-pool
