config:
  availableDatasets:
    - "dp02"
    - "dp03"
    - "dp1"
    - "efd"
    - "live"
  hips:
    datasets: {}
  tap:
    schemaVersion: "w.2026.28"
    schemaSourceTemplate: "https://github.com/lsst/sdm_schemas/archive/refs/tags/{version}.tar.gz"
    servers:
      tap:
        enabled: true
        databaseUrl: "postgresql://tap_schema_admin_tap@rsp-db-rw.postgres-db:5432/tap"
        databasePasswordKey: "tap-schema-admin-password"
      ssotap:
        enabled: true
        databaseUrl: "postgresql://tap_schema_admin_ssotap@rsp-db-rw.postgres-db:5432/ssotap"
        databasePasswordKey: "ssotap-schema-admin-password"
      livetap:
        enabled: true
        databaseUrl: "postgresql://tap_schema_admin_livetap@rsp-db-rw.postgres-db:5432/livetap"
        databasePasswordKey: "livetap-schema-admin-password"
      consdbtap:
        enabled: true
        databaseUrl: "postgresql://tap_schema_admin_consdbtap@rsp-db-rw.postgres-db:5432/consdbtap"
        databasePasswordKey: "consdbtap-schema-admin-password"
  influxdbDatabases:
    usdfdev_efd:
      url: "https://usdf-rsp-dev.slac.stanford.edu/influxdb/"
      database: "efd"
      username: "efdreader"
      passwordKey: "usdfdev_efd-password"
      schemaRegistry: "http://sasquatch-schema-registry.sasquatch:8081"
      local: true
