config:
  availableDatasets:
    - "dp02"
    - "dp03"
    - "dp1"
    - "dp2"
    - "prompt"
  hips:
    legacy:
      dataset: "dp1"
  metrics:
    enabled: true
  rules:
    gafaelfawr:
      ui:
        comanage:
          title: "Account settings"
          template: "https://id.lsst.cloud/"
    times-square:
      internal:
        times-square:
          requiredScopes:
            - "exec:admin"
  slackAlerts: true
  tap:
    servers:
      tap:
        enabled: true
      ssotap:
        enabled: true
  useSubdomains:
    - "nublado"

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-stable-6994:us-central1:science-platform-stable-0c29612b"
  serviceAccount: "repertoire@science-platform-stable-6994.iam.gserviceaccount.com"
