config:
  availableDatasets:
    - "dp02"
    - "dp03"
    - "dp1"
    - "dp2"
    - "prompt"
  hips:
    legacy:
      dataset: "dp1"
  metrics:
    enabled: true
  slackAlerts: true
  tap:
    schemaVersion: "main"
    servers:
      tap:
        enabled: true
        schemas:
          - dp2
          - dp1
          - ivoa_obscore
          - dp02_dc2
      ssotap:
        enabled: true
  useSubdomains:
    - "nublado"

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-int-dc5d:us-central1:science-platform-int-8f439af2"
  serviceAccount: "repertoire@science-platform-int-dc5d.iam.gserviceaccount.com"
