config:
  availableDatasets:
    - "dp02"
    - "dp03"
    - "dp1"
    - "dp2"
    - "prompt"
  hips:
    legacy:
      dataset: "dp1"
  influxdbDatabases:
    idfdev_efd:
      url: "https://data-dev.lsst.cloud/influxdb/"
      database: "efd"
      username: "efdreader"
      passwordKey: "idfdev_efd-password"
      schemaRegistry: "http://sasquatch-schema-registry.sasquatch:8081"
      local: true
  metrics:
    enabled: true
  rules:
    # Override the required scope of times-square. Unfortunately, there is no
    # way to do this at the moment without duplicating the entry.
    times-square:
      - type: "internal"
        name: "times-square"
        requiredScopes:
          - "exec:admin"
        template: "https://{{base_hostname}}/times-square/api"
        openapi: "https://{{base_hostname}}/times-square/api/openapi.json"
        docsUrl: "https://times-square.lsst.io/"
        versions:
          v1:
            template: "https://{{base_hostname}}/times-square/api/v1"
  slackAlerts: true
  tap:
    servers:
      ppdbtap:
        enabled: true
        schemaVersion: "releases/w.2026.38"
      ssotap:
        enabled: true
      tap:
        enabled: true
        schemaVersion: "tickets/DM-54475"
      obsforgetap:
        enabled: true
  useSubdomains:
    - "nublado"

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
  serviceAccount: "repertoire@science-platform-dev-7696.iam.gserviceaccount.com"
