config:
  availableDatasets:
    - "dp02"
    - "dp03"
    - "dp1"
    - "efd"
    - "live"
  hips:
    datasets: {}
  tap:
    servers:
      tap:
        databaseUrl: "postgresql://tap_schema_admin_tap@rsp-db.postgres-db:5432/tap"
        databasePasswordKey: "tap-schema-admin-password"
  influxdbDatabases:
    usdfdev_efd:
      url: "https://usdf-rsp-dev.slac.stanford.edu/influxdb/"
      database: "efd"
      username: "efdreader"
      passwordKey: "usdfdev_efd-password"
      schemaRegistry: "http://sasquatch-schema-registry.sasquatch:8081"
      local: true
