{{- if (index .Values "applications" "ephemcache") -}}
apiVersion: v1
kind: Namespace
metadata:
  name: "ephemcache"
  {{- if .Values.defaultComputeClass }}
  labels:
    cloud.google.com/default-compute-class: {{ .Values.defaultComputeClass | quote }}
  {{- end}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "ephemcache"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "ephemcache"
    server: "https://kubernetes.default.svc"
  project: "rubin"
  source:
    path: "applications/ephemcache"
    repoURL: {{ .Values.repoUrl | quote }}
    targetRevision: {{ or (index .Values "revisions" "ephemcache") .Values.targetRevision | quote }}
    helm:
      parameters:
        - name: "global.baseUrl"
          value: "https://{{ .Values.fqdn }}"
        - name: "global.environmentName"
          value: {{ .Values.name | quote }}
        - name: "global.host"
          value: {{ .Values.fqdn | quote }}
        - name: "global.repertoireUrl"
          value: "https://{{ .Values.fqdn }}/repertoire"
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vaultPathPrefix | quote }}
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.name }}.yaml"
{{- end -}}