apiVersion: v1
kind: ConfigMap
metadata:
  name: "semaphore"
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
data:
  SEMAPHORE_ENABLE_GITHUB_APP: {{ .Values.config.enableGithubApp | quote }}
  SEMAPHORE_GITHUB_APP_ID: {{ .Values.config.githubAppId | quote }}
  SEMAPHORE_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  SEMAPHORE_LOG_PROFILE: {{ .Values.config.logProfile | quote }}
  SEMAPHORE_PATH_PREFIX: {{ .Values.config.pathPrefix | quote }}
  SEMAPHORE_PHALANX_ENV: {{ .Values.global.environmentName | quote }}
