apiVersion: apps/v1
kind: Deployment
metadata:
  name: "semaphore"
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "semaphore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "semaphore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: "SEMAPHORE_GITHUB_WEBHOOK_SECRET"
              valueFrom:
                secretKeyRef:
                  name: "semaphore"
                  key: "SEMAPHORE_GITHUB_WEBHOOK_SECRET"
            - name: "SEMAPHORE_GITHUB_APP_PRIVATE_KEY"
              valueFrom:
                secretKeyRef:
                  name: "semaphore"
                  key: "SEMAPHORE_GITHUB_APP_PRIVATE_KEY"
            {{- if .Values.config.slackAlerts }}
            - name: "SEMAPHORE_SLACK_WEBHOOK"
              valueFrom:
                secretKeyRef:
                  name: "semaphore"
                  key: "slack-webhook"
            {{- end }}
          envFrom:
            - configMapRef:
                name: "semaphore"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          livenessProbe:
            httpGet:
              path: "/"
              port: "http"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/"
              port: "http"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - "all"
            readOnlyRootFilesystem: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
