apiVersion: apps/v1
kind: Deployment
metadata:
  name: "semaphore"
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "semaphore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "semaphore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: "SEMAPHORE_GITHUB_WEBHOOK_SECRET"
              valueFrom:
                secretKeyRef:
                  name: "semaphore"
                  key: "SEMAPHORE_GITHUB_WEBHOOK_SECRET"
            - name: "SEMAPHORE_GITHUB_APP_PRIVATE_KEY"
              valueFrom:
                secretKeyRef:
                  name: "semaphore"
                  key: "SEMAPHORE_GITHUB_APP_PRIVATE_KEY"
            {{- if .Values.config.slackAlerts }}
            - name: "SEMAPHORE_SLACK_WEBHOOK"
              valueFrom:
                secretKeyRef:
                  name: "semaphore"
                  key: "slack-webhook"
            {{- end }}
            {{- if .Values.config.sentry.enabled }}
            - name: "SENTRY_DSN"
              valueFrom:
                secretKeyRef:
                  name: "semaphore"
                  key: "sentry-dsn"
            - name: "SENTRY_ENVIRONMENT"
              value: {{ .Values.global.environmentName }}
            - name: "SENTRY_TRACES_SAMPLE_RATE"
              value: {{ .Values.config.sentry.tracesSampleRate }}
            {{- end }}
            # Uvicorn keepalive timeout, in seconds. This should be longer
            # than any keepalive timeouts on any downstream proxies. The
            # keepalive timeout for ingress-nginx connections is 60s.
            - name: "UVICORN_TIMEOUT_KEEP_ALIVE"
              value: "61"
          envFrom:
            - configMapRef:
                name: "semaphore"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          lifecycle:
            # Number of seconds k8s should wait before sending SIGTERM on
            # graceful restarts/deployments/shutdowns. We need this because it
            # takes ingress-nginx some time to configure itself to stop
            # sending traffic to the pods scheduled for termination. If
            # Uvicorn gets the SIGTERM and starts closing connections, we
            # could end up with a TCP race condition if ingress-nginx still
            # tries to send data over those connections.
            #
            # Note that terminationGracePeriodSeconds includes the time that
            # is spent in the preStop hook. If you’re adding a preStop hook
            # and your terminationGracePeriodSeconds is super fine-tuned, then
            # you should update your terminationGracePeriodSeconds to add the
            # amount of time you’ll be spending in your preStop hook.
            preStop:
              sleep:
                seconds: 10
          livenessProbe:
            httpGet:
              path: "/"
              port: "http"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/"
              port: "http"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - "all"
            readOnlyRootFilesystem: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
