apiVersion: apps/v1
kind: Deployment
metadata:
  name: "herald"
  labels:
    {{- include "herald.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "herald.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "herald.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- if .Values.config.metrics.enabled }}
            - name: "KAFKA_BOOTSTRAP_SERVERS"
              valueFrom:
                secretKeyRef:
                  name: "herald-kafka"
                  key: "bootstrapServers"
            - name: "KAFKA_CLIENT_CERT_PATH"
              value: "/etc/herald-kafka/user.crt"
            - name: "KAFKA_CLIENT_KEY_PATH"
              value: "/etc/herald-kafka/user.key"
            - name: "KAFKA_CLUSTER_CA_PATH"
              value: "/etc/herald-kafka/ca.crt"
            - name: "KAFKA_SECURITY_PROTOCOL"
              valueFrom:
                secretKeyRef:
                  name: "herald-kafka"
                  key: "securityProtocol"
            {{- end }}
            {{- if .Values.config.s3Credentials }}
            - name: "HERALD_AWS_ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  name: "herald"
                  key: "aws-access-key-id"
            - name: "HERALD_AWS_SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: "herald"
                  key: "aws-secret-access-key"
            {{- end }}
            {{- if .Values.config.slackAlerts }}
            - name: "HERALD_SLACK_WEBHOOK"
              valueFrom:
                secretKeyRef:
                  name: "herald"
                  key: "slack-webhook"
            {{- end }}
            # Uvicorn keepalive timeout, in seconds. This should be longer
            # than any keepalive timeouts on any downstream proxies. The
            # keepalive timeout for ingress-nginx connections is 60s.
            - name: "UVICORN_TIMEOUT_KEEP_ALIVE"
              value: "61"
          envFrom:
            - configMapRef:
                name: "herald"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            # Number of seconds k8s should wait before sending SIGTERM on
            # graceful restarts/deployments/shutdowns. We need this because it
            # takes ingress-nginx some time to configure itself to stop
            # sending traffic to the pods scheduled for termination. If
            # Uvicorn gets the SIGTERM and starts closing connections, we
            # could end up with a TCP race condition if ingress-nginx still
            # tries to send data over those connections.
            preStop:
              sleep:
                seconds: 10
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/"
              port: "http"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
          {{- if .Values.config.metrics.enabled }}
          volumeMounts:
            - name: "kafka"
              mountPath: "/etc/herald-kafka/ca.crt"
              readOnly: true
              subPath: "ssl.truststore.crt"
            - name: "kafka"
              mountPath: "/etc/herald-kafka/user.crt"
              readOnly: true
              subPath: "ssl.keystore.crt"
            - name: "kafka"
              mountPath: "/etc/herald-kafka/user.key"
              readOnly: true
              subPath: "ssl.keystore.key"
          {{- end }}
      {{- if .Values.config.metrics.enabled }}
      volumes:
        - name: "kafka"
          secret:
            secretName: "herald-kafka"
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
