{{- if or .Values.config.s3Credentials .Values.config.slackAlerts -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "herald"
  labels:
    {{- include "herald.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/herald"
  type: Opaque
{{- end }}
