test42:
  image:
    repository: ts-dockerhub.lsst.org/test
  env:
    RUN_ARG: 42
  resources:
    limits:
      cpu: 150m
      memory: 300Mi
    requests:
      cpu: 15m
      memory: 95Mi

integration-testing:
  enabled: true
  envEfd: base_efd
  s3Bucket: rubinobs-lfa-ls

rumba:
  enabled: true

kafka-rw-broker-test:
  enabled: true
  image:
    tag: 0.47.0-kafka-3.9.1
  test:
    numRecords: "5000000"
    recordSize: 1024
    throughput: 50000
    timeoutMs: 240000
  kafka:
    partitions: 32
