internalDB: true
config:
  logLevel: "INFO"
  logProfile: "development"
  db:
    hostname: "postgres.postgres"
    echo: true
  outputVolume:
    storageClassName: "sdf-data-rubin"
    subPath: "shared/campaigns/users/usdf-cm-dev"
image:
  tag: "tickets-DM-48099-release"
  pullPolicy: Always
worker:
  image:
    tag: "tickets-DM-48099-release"
    pullPolicy: Always
  htcondor:
    config:
      mountPath: "/home/lsstsvc1/.config/condor"
      contents: |
        CONDOR_HOST = sdfiana012.sdf.slac.stanford.edu
        COLLECTOR_HOST = sdfiana012.sdf.slac.stanford.edu
        SCHEDD_HOST = sdfiana012.sdf.slac.stanford.edu
        SEC_CLIENT_AUTHENTICATION_METHODS = FS, FS_REMOTE
        use security:recommended_v9_0
        SEC_DEFAULT_AUTHENTICATION_METHODS = FS_REMOTE, IDTOKENS, FS
        SEC_DAEMON_AUTHENTICATION_METHODS = FS_REMOTE, IDTOKENS, FS
        SEC_READ_AUTHENTICATION_METHODS = FS_REMOTE, IDTOKENS, FS
        FS_REMOTE_DIR = /sdf/group/rubin/services/htcondor/shared
    fsRemoteDir:
      storageClassName: "sdf-group-rubin"
      subPath: "services/htcondor/shared"
      mountPath: "/sdf/group/rubin/services/htcondor/shared"
