apiVersion: apps/v1
kind: Deployment
metadata:
  name: "sia"
  labels:
    {{- include "sia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sia.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: "sia"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: {{ .Values.config.pathPrefix }}/availability
              port: "http"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: "SIA_BUTLER_TYPE"
              value: {{ .Values.config.butlerType | quote }}
            - name: "SIA_BUTLER_DATA_COLLECTIONS"
              value: {{ .Values.config.butlerDataCollections | toJson | quote }}
            {{- if .Values.config.slackAlerts }}
            - name: "SIA_SLACK_WEBHOOK"
              valueFrom:
                secretKeyRef:
                  name: "sia"
                  key: "slack-webhook"
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
