apiVersion: gafaelfawr.lsst.io/v1alpha1
kind: GafaelfawrIngress
metadata:
  name: "sia-anonymous"
  labels:
    {{- include "sia.labels" . | nindent 4 }}
config:
  scopes:
    anonymous: true
template:
  metadata:
    name: "sia-anonymous"
    {{- with .Values.ingress.annotations }}
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      {{- toYaml . | nindent 6 }}
    {{- end }}
  spec:
    rules:
      - host: {{ .Values.global.host | quote }}
        http:
          paths:
            - path: "{{ .Values.config.pathPrefix }}/openapi.json"
              pathType: "Exact"
              backend:
                service:
                  name: "sia"
                  port:
                    number: 8080
            - path: "{{ .Values.config.pathPrefix }}/.+/capabilities"
              pathType: "ImplementationSpecific"
              backend:
                service:
                  name: "sia"
                  port:
                    number: 8080
            - path: "{{ .Values.config.pathPrefix }}/.+/availability"
              pathType: "ImplementationSpecific"
              backend:
                service:
                  name: "sia"
                  port:
                    number: 8080
