strimzi-kafka:
  kraft:
    enabled: true
  kafkaController:
    enabled: true
  kafka:
    version: "3.9.0"
    config:
      log.retention.minutes: 10080
      offsets.retention.minutes: 10080
    listeners:
      tls:
        enabled: true
      plain:
        enabled: true
      external:
        enabled: true
        externalListener:
          bootstrap:
            annotations:
              metallb.io/address-pool: sdf-rubin-ingest
          brokers:
            - broker: 0
              annotations:
                metallb.io/address-pool: sdf-rubin-ingest
            - broker: 1
              annotations:
                metallb.io/address-pool: sdf-rubin-ingest
            - broker: 2
              annotations:
                metallb.io/address-pool: sdf-rubin-ingest
    storage:
      size: 100Gi
      storageClassName: wekafs--sdf-k8s01

kafdrop:
  ingress:
    enabled: true
    hostname: usdfdev-prompt-processing.slac.stanford.edu
