{{- if .Values.config.slackAlerts -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "hips"
  labels:
    {{- include "hips.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/hips"
  type: Opaque
{{- end }}
