cadc-tap:
  nodeSelector:
    node_pool: "arm-core-pool"

  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfdemo-tap"
      tag: "tickets-DM-52731"
      pullPolicy: "Always"

  config:
    qserv:
      host: "qserv-int.slac.stanford.edu:4090"
      jdbcParams: "?enabledTLSProtocols=TLSv1.3"
      passwordEnabled: true
      image:
        tag: "tickets-DM-52819"
        pullPolicy: "Always"
    pg:
      image:
        tag: "tickets/DM-52731"
        pullPolicy: "Always"

    kafka:
      enabled: false

    urlRewrite:
      enabled: true
      rules: "ivoa.ObsCore:access_url, dp02_dc2_catalogs.ObsCore:access_url, dp1.ObsCore:access_url"
    gcsBucket: "https://async-results.lsst.codes"
    gcsBucketUrl: "https://tap-files.lsst.codes"
    datalinkPayloadUrl: "https://github.com/lsst/sdm_schemas/releases/download/DP1-v1.1.4-rc1/datalink-snippets.zip"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-demo-9e05:us-central1:science-platform-demo-a4dbbf96"
    serviceAccount: "tap-service@science-platform-demo-9e05.iam.gserviceaccount.com"
    database: "tap"
