cadc-tap:
  tapSchema:
    type: "external"
    database: "tap"
    username: "tap_schema_tap"
    useVaultPassword: true
    external:
      host: "rsp-db-ro.postgres-db"

  uws:
    type: "external"
    database: "tap"
    username: "uws_tap"
    useVaultPassword: true
    external:
      host: "rsp-db-rw.postgres-db"

  config:
    qserv:
      host: "sdfqserv001.sdf.slac.stanford.edu:4090"
      jdbcParams: "?enabledTLSProtocols=TLSv1.3"
      passwordEnabled: true

    kafka:
      enabled: true

    urlRewrite:
      enabled: true
      rules:
        - "ivoa.ObsCore:access_url"
        - "dp02_dc2_catalogs.ObsCore:access_url"
        - "dp1.ObsCore:access_url"

    gcsBucket: "rubin:rubin-qserv"
    gcsBucketUrl: "https://s3dfrgw.slac.stanford.edu"
    gcsBucketType: "S3"
    jvmMaxHeapSize: "31G"
