cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-usdf-prod-tap"
    type: "containerized"
    database: "TAP_SCHEMA"
    username: "TAP_SCHEMA"
    useVaultPassword: false

  uws:
    type: "containerized"
    database: "postgres"
    username: "postgres"
    useVaultPassword: false

  config:
    qserv:
      host: "sdfqserv001.sdf.slac.stanford.edu:4040"
      jdbcParams: "?enabledTLSProtocols=TLSv1.3"
      passwordEnabled: true
      image:
        tag: "2.14.0"

    gcsBucket: "rubin:rubin-qserv"
    gcsBucketUrl: "https://s3dfrgw.slac.stanford.edu"
    gcsBucketType: "S3"
