apiVersion: v2
name: strimzi
type: application
version: 1.0.0
description: Strimzi Kafka Operator
home: https://strimzi.io
dependencies:
  - name: strimzi-kafka-operator
    version: "0.46.0"
    repository: https://strimzi.io/charts/
