weaviate:
  service:
    type: LoadBalancer
    annotations:
      metallb.io/address-pool: sdf-services
    allocateLoadBalancerNodePorts: false
  grpcService:
    type: ClusterIP
  storage:
    size: 500Gi
image:
  tag: "tickets-DM-55408"
  pullPolicy: Always
