apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "google-cloud-observability"
  labels:
    {{- include "google-cloud-observability.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/google-cloud-observability"
  type: Opaque
