replicaCount: 3

ingress:
  timesSquareScope: "exec:admin"

config:
  docsBaseUrl: "https://rsp.lsst.io"
  timesSquareUrl: "https://data.lsst.cloud/times-square/api"
  plausibleDomain: "data.lsst.cloud"
  enableSentry: true
  sentryTracesSampleRate: 1.0
  sentryReplaysOnErrorSampleRate: 1.0
  enableUserNotifications: true
