image:
  pullPolicy: Always

ingress:
  timesSquareScope: "exec:admin"

config:
  docsBaseUrl: "https://rsp.lsst.io/v/idfdev"
  enableUserNotifications: true
  plausibleDomain: "data-dev.lsst.cloud"
  headerLogoFile: "demo-logo.png"
  headerLogoHeight: 50
  headerLogoWidth: 240

  enableSentry: true
  sentryTracesSampleRate: 1.0
  sentryReplaysOnErrorSampleRate: 1.0
  enableAppsMenu: true
