# Makefile for Sphinx documentation.
# Use tox -e docs,docs-linkcheck to build the docs.

.PHONY: help
help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  clean      delete builds"

.PHONY: clean
clean:
	rm -rf _build/*
