# Default values for docverse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  # -- Number of API deployment pods to start
  api: 1

  # -- Number of worker deployment pods to start
  worker: 1

image:
  # -- Image to use in the docverse deployment
  repository: "ghcr.io/lsst-sqre/docverse"

  # -- Pull policy for the docverse image
  pullPolicy: "IfNotPresent"

  # -- Tag of image to use
  # @default -- The appVersion of the chart
  tag: null

config:
  # -- Logging level
  logLevel: "INFO"

  # -- Logging profile (`production` for JSON, `development` for
  # human-friendly)
  logProfile: "production"

  # -- URL path prefix
  pathPrefix: "/docverse/api"

  # -- Whether to send Slack alerts for unexpected failures
  slackAlerts: false

  # -- Database URL for PostgreSQL
  databaseUrl: ""

  # -- URL for Redis arq queue database
  # @default -- Points to embedded Redis
  arqRedisUrl: "redis://docverse-redis:6379/0"

  # -- Whether to run Alembic schema migrations on install/upgrade
  updateSchema: false

  # -- Usernames that have super admin (de facto admin in all organizations)
  superadminUsers:
    - "jonathansick"

ingress:
  # -- Additional annotations for the ingress rule
  annotations: {}

# -- Affinity rules for the docverse deployment pod
affinity: {}

# -- Node selection rules for the docverse deployment pod
nodeSelector: {}

# -- Annotations for the docverse deployment pod
podAnnotations: {}

# -- Resource limits and requests for the docverse deployment pod
# @default -- See `values.yaml`
resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    # -- GKE Autopilot requires a minimum CPU request of 50m
    cpu: "50m"
    memory: "100Mi"

# -- Resource limits and requests for the docverse worker pod
# @default -- See `values.yaml`
workerResources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    # -- GKE Autopilot requires a minimum CPU request of 50m
    cpu: "50m"
    memory: "128Mi"

# -- Tolerations for the docverse deployment pod
tolerations: []

cloudsql:
  # -- Enable the Cloud SQL Auth Proxy sidecar, used with Cloud SQL databases
  # on Google Cloud
  enabled: false

  image:
    # -- Cloud SQL Auth Proxy image to use
    repository: "gcr.io/cloudsql-docker/gce-proxy"

    # -- Cloud SQL Auth Proxy tag to use
    tag: "1.37.14"

    # -- Pull policy for Cloud SQL Auth Proxy images
    pullPolicy: "IfNotPresent"

  # -- Resource requests and limits for Cloud SQL Auth Proxy
  # @default -- See `values.yaml`
  resources:
    limits:
      cpu: "100m"
      memory: "30Mi"
    requests:
      cpu: "5m"
      memory: "15Mi"

  # -- Instance connection name for a Cloud SQL PostgreSQL instance
  instanceConnectionName: ""

  # -- The Google service account that has an IAM binding to the `docverse`
  # Kubernetes service accounts and has the `cloudsql.client` role
  serviceAccount: ""

redis:
  persistence:
    # -- Whether to persist Redis storage. Setting this to false will use
    # `emptyDir` and lose data on every restart.
    enabled: true

    # -- Amount of persistent storage to request
    size: "1Gi"

    # -- Class of storage to request
    storageClass: ""

    # -- Use an existing PVC, not dynamic provisioning. If this is set, the
    # size, storageClass, and accessMode settings are ignored.
    volumeClaimName: ""

  # -- Resource limits and requests for the Redis pod
  # @default -- See `values.yaml`
  resources:
    limits:
      cpu: "1"
      memory: "256Mi"
    requests:
      # -- GKE Autopilot requires a minimum CPU request of 50m
      cpu: "50m"
      memory: "64Mi"

  # -- Pod annotations for the Redis pod
  podAnnotations: {}

  # -- Node selection rules for the Redis pod
  nodeSelector: {}

  # -- Tolerations for the Redis pod
  tolerations: []

  # -- Affinity rules for the Redis pod
  affinity: {}

# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: null

  # -- Base URL for Repertoire discovery API
  # @default -- Set by Argo CD
  repertoireUrl: null

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: null
