config:
  databaseUrl: "postgresql://docverse@localhost/docverse"

cloudsql:
  enabled: true
  instanceConnectionName: "roundtable-prod-f6fd:us-central1:roundtable-prod-f119ac3d"
  serviceAccount: "docverse-sa@roundtable-prod-f6fd.iam.gserviceaccount.com"
