{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "river-next.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "river-next.labels" -}}
helm.sh/chart: {{ include "river-next.chart" . }}
{{ include "river-next.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels shared by every workload in the chart
*/}}
{{- define "river-next.selectorLabels" -}}
app.kubernetes.io/name: "river-next"
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Selector labels for the front-end pod. The chart also runs a ClickHouse
workload, so the front-end's Deployment, Service and NetworkPolicy select on a
component label as well; selecting on the shared labels alone would also match
the ClickHouse pods.
*/}}
{{- define "river-next.frontend.selectorLabels" -}}
{{ include "river-next.selectorLabels" . }}
app.kubernetes.io/component: "frontend"
{{- end }}

{{/*
Public base URL the service advertises in the URLs it generates. Defaults to the
environment's base URL plus the ingress path prefix, which is what the ingress
actually serves; `config.baseUrl` overrides it when the two must differ.
*/}}
{{- define "river-next.baseUrl" -}}
{{- if .Values.config.baseUrl -}}
{{- .Values.config.baseUrl -}}
{{- else -}}
{{- printf "%s%s" (required "global.baseUrl or config.baseUrl must be set" .Values.global.baseUrl) .Values.ingress.pathPrefix -}}
{{- end -}}
{{- end }}

{{/*
The mppdb TOML configuration file. Only the `[databases]` catalog (and the
optional `[branding]` table) live here: mppdb reads the catalog *only* from the
TOML file, while every flat scalar setting comes from the environment, where it
is easier to override per environment. `registry` paths are resolved against
`config.registryDir`, a directory baked into the image.
*/}}
{{- define "river-next.mppdbToml" -}}
# Generated by the river-next Helm chart. Edit applications/river-next/values.yaml,
# never this file: it is replaced on every sync.
{{- with .Values.config.defaultDatabase }}
default_database = {{ . | quote }}
{{- end }}
advertise_request_base = {{ .Values.config.advertiseRequestBase }}
{{- range $name, $db := .Values.config.databases }}

[databases.{{ $name }}]
ch_database = {{ required (printf "config.databases.%s.chDatabase must be set" $name) $db.chDatabase | quote }}
{{- with $db.manifestsDir }}
manifests_dir = {{ . | quote }}
{{- end }}
{{- with $db.lakeDir }}
lake_dir = {{ . | quote }}
{{- end }}
{{- with $db.registry }}
registry = {{ printf "%s/%s" (trimSuffix "/" $.Values.config.registryDir) . | quote }}
{{- end }}
{{- end }}
{{- with .Values.config.branding }}

[branding]
{{- range $key, $value := . }}
{{ $key }} = {{ $value | quote }}
{{- end }}
{{- if not (hasKey . "public_url") }}
public_url = {{ include "river-next.baseUrl" $ | quote }}
{{- end }}
{{- end }}
{{- end }}

{{/*
ClickHouse: common labels. The chart's shared labels plus a component label.
*/}}
{{- define "river-next.clickhouse.labels" -}}
{{ include "river-next.labels" . }}
app.kubernetes.io/component: "clickhouse"
{{- end }}

{{/*
ClickHouse: selector labels. The chart's shared selector labels match every
pod in the chart, so ClickHouse selectors always add the component label.
*/}}
{{- define "river-next.clickhouse.selectorLabels" -}}
{{ include "river-next.selectorLabels" . }}
app.kubernetes.io/component: "clickhouse"
{{- end }}

{{/*
ClickHouse: the memory limit in bytes. Accepts a plain number of bytes or a
Kubernetes quantity with a k, M, G, T, Ki, Mi, Gi or Ti suffix, and fails
rendering on anything else.
*/}}
{{- define "river-next.clickhouse.memoryLimitBytes" -}}
{{- $raw := required "clickhouse.resources.limits.memory must be set" .Values.clickhouse.resources.limits.memory -}}
{{- $num := 0.0 -}}
{{- $suffix := "" -}}
{{- if or (kindIs "float64" $raw) (kindIs "int" $raw) (kindIs "int64" $raw) -}}
{{- $num = float64 $raw -}}
{{- else -}}
{{- $s := toString $raw -}}
{{- if not (regexMatch "^[0-9]+(\\.[0-9]+)?(Ki|Mi|Gi|Ti|k|M|G|T)?$" $s) -}}
{{- fail (printf "clickhouse.resources.limits.memory %q cannot be parsed: use a number of bytes, or a number with a k, M, G, T, Ki, Mi, Gi or Ti suffix" $s) -}}
{{- end -}}
{{- $digits := regexFind "^[0-9]+(\\.[0-9]+)?" $s -}}
{{- $num = float64 $digits -}}
{{- $suffix = trimPrefix $digits $s -}}
{{- end -}}
{{- $multipliers := dict "" 1.0 "k" 1e3 "M" 1e6 "G" 1e9 "T" 1e12 "Ki" 1024.0 "Mi" 1048576.0 "Gi" 1073741824.0 "Ti" 1099511627776.0 -}}
{{- printf "%.0f" (mulf $num (index $multipliers $suffix) | floor) -}}
{{- end }}

{{/*
ClickHouse: max_server_memory_usage in bytes, the configured ratio of the
memory limit.
*/}}
{{- define "river-next.clickhouse.maxServerMemoryUsage" -}}
{{- $ratio := float64 .Values.clickhouse.maxServerMemoryUsageRatio -}}
{{- if or (le $ratio 0.0) (gt $ratio 1.0) -}}
{{- fail (printf "clickhouse.maxServerMemoryUsageRatio must be greater than 0 and at most 1, not %v" .Values.clickhouse.maxServerMemoryUsageRatio) -}}
{{- end -}}
{{- $bytes := float64 (include "river-next.clickhouse.memoryLimitBytes" .) -}}
{{- printf "%.0f" (mulf $bytes $ratio | floor) -}}
{{- end }}

{{/*
ClickHouse: max_threads. clickhouse.maxThreads if set, which must then be a
positive integer; otherwise (unset, null or 0) the integer part of the CPU
limit, which may be given in cores or millicores. Never 0, which ClickHouse
would read as "auto" and size to every host core.
*/}}
{{- define "river-next.clickhouse.maxThreads" -}}
{{- $set := .Values.clickhouse.maxThreads -}}
{{- if and (not (kindIs "invalid" $set)) (not (and (or (kindIs "float64" $set) (kindIs "int" $set) (kindIs "int64" $set)) (eq (float64 $set) 0.0))) -}}
{{- include "river-next.clickhouse.positiveInteger" (list "clickhouse.maxThreads" $set) -}}
{{- else -}}
{{- $raw := required "clickhouse.resources.limits.cpu must be set" .Values.clickhouse.resources.limits.cpu -}}
{{- $cores := 0.0 -}}
{{- if or (kindIs "float64" $raw) (kindIs "int" $raw) (kindIs "int64" $raw) -}}
{{- $cores = float64 $raw -}}
{{- else -}}
{{- $s := toString $raw -}}
{{- if regexMatch "^[0-9]+(\\.[0-9]+)?$" $s -}}
{{- $cores = float64 $s -}}
{{- else if regexMatch "^[0-9]+m$" $s -}}
{{- $cores = divf (float64 (trimSuffix "m" $s)) 1000.0 -}}
{{- else -}}
{{- fail (printf "clickhouse.resources.limits.cpu %q cannot be parsed: use a number of cores or of millicores (such as 64 or 64000m)" $s) -}}
{{- end -}}
{{- end -}}
{{- max 1 (int (floor $cores)) -}}
{{- end -}}
{{- end }}

{{/*
ClickHouse: a value that must be a positive integer, printed in decimal.
Called with (list "<value name>" <value>); fails rendering on anything else,
including strings, fractions, zero and negative numbers.
*/}}
{{- define "river-next.clickhouse.positiveInteger" -}}
{{- $name := index . 0 -}}
{{- $v := index . 1 -}}
{{- $ok := false -}}
{{- if or (kindIs "int" $v) (kindIs "int64" $v) -}}
{{- $ok = gt (int64 $v) 0 -}}
{{- else if kindIs "float64" $v -}}
{{- $ok = and (gt $v 0.0) (eq $v (floor $v)) -}}
{{- end -}}
{{- if not $ok -}}
{{- fail (printf "%s must be a positive integer, not %#v" $name $v) -}}
{{- end -}}
{{- printf "%.0f" (float64 $v) -}}
{{- end }}
