apiVersion: v1
kind: Service
metadata:
  name: "river-next-clickhouse"
  labels:
    {{- include "river-next.clickhouse.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8123
      targetPort: "http"
      protocol: "TCP"
      name: "http"
    - port: 9000
      targetPort: "native"
      protocol: "TCP"
      name: "native"
  selector:
    {{- include "river-next.clickhouse.selectorLabels" . | nindent 4 }}
