apiVersion: apps/v1
kind: Deployment
metadata:
  name: "octavius-ui-deploy"
  labels:
    {{- include "octavius.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount_ui }}
  selector:
    matchLabels:
      {{- include "octavius.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "octavius.selectorLabels" . | nindent 8 }}
        component: "frontend"
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}-ui
          env:
            {{- if .Values.config.slackAlerts }}
            - name: "OCTAVIUS_SLACK_WEBHOOK"
              valueFrom:
                secretKeyRef:
                  name: "octavius-secrets"
                  key: "slack-webhook"
            {{- end }}
            # Uvicorn keepalive timeout, in seconds. This should be longer
            # than any keepalive timeouts on any downstream proxies. The
            # keepalive timeout for ingress-nginx connections is 60s.
            - name: "UVICORN_TIMEOUT_KEEP_ALIVE"
              value: "61"
            - name: "API_HOST"
              value: "octavius-api"
            - name: "REACT_APP_API_URL"
              value: "https://octavius-api:8443"
            - name: "API_URL"
              value: "https://octavius-api:8443"
            - name: "AZURE_STORAGE_ACCOUNT_NAME"
              valueFrom:
                secretKeyRef:
                  name: octavius-secrets
                  key: "az-storage-ac-name"
            - name: "AZURE_STORAGE_ACCOUNT_KEY"
              valueFrom:
                secretKeyRef:
                  name: octavius-secrets
                  key: "az-storage-ac-key"
          image: "{{ .Values.imageUI.repository }}:{{ .Values.imageUI.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageUI.pullPolicy }}
          lifecycle:
            preStop:
              sleep:
                seconds: 10
          ports:
            - name: "http"
              containerPort: 80
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/octavius/"
              port: "http"
              initialDelaySeconds: 30
              periodSeconds: 5
              timeoutSeconds: 2
              failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
