apiVersion: apps/v1
kind: Deployment
metadata:
  name: "octavius-api-deploy"
  labels:
    {{- include "octavius.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount_api }}
  selector:
    matchLabels:
      {{- include "octavius.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "octavius.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}-api
          env:
            {{- if .Values.config.slackAlerts }}
            - name: "OCTAVIUS_SLACK_WEBHOOK"
              valueFrom:
                secretKeyRef:
                  name: octavius-secrets"
                  key: "slack-webhook"
            {{- end }}
            # Uvicorn keepalive timeout, in seconds. This should be longer
            # than any keepalive timeouts on any downstream proxies. The
            # keepalive timeout for ingress-nginx connections is 60s.
            - name: "UVICORN_TIMEOUT_KEEP_ALIVE"
              value: "61"
            - name: "API_PORT"
              value: "8443"
            - name: "MONGO_URL"
              valueFrom:
                secretKeyRef:
                  name: octavius-secrets
                  key: "api-mongo-url"
          image: "{{ .Values.imageAPI.repository }}:{{ .Values.imageAPI.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageAPI.pullPolicy }}
          lifecycle:
            preStop:
              sleep:
                seconds: 10
          ports:
            - name: "http"
              containerPort: 8443
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/heartbeat"
              port: "http"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
