replicaCount: 8

config:
  profiles:
    - name: embargo
      url: "https://sdfembs3.sdf.slac.stanford.edu/"
    - name: hips
      url: "https://sdfdatas3.slac.stanford.edu/"
  s3EndpointUrl: "https://s3dfrgw.slac.stanford.edu/"
  cacheMaxAge: 86400

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 256Mi
