cadc-tap:
  tapSchema:
    type: "external"
    database: "livetap"
    username: "tap_schema_livetap"
    useVaultPassword: true
    external:
      host: "rsp-db-ro.postgres-db"

  uws:
    type: "external"
    database: "livetap"
    username: "uws_livetap"
    useVaultPassword: true
    external:
      host: "rsp-db-rw.postgres-db"
