{{- if .Values.config.slackAlerts -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "prompt-processing-kafka"
  labels:
    {{- include "prompt-processing-kafka.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/prompt-processing-kafka"
  type: Opaque
{{- end }}
