{{- if .Values.config.slackAlerts -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "so-evening-tailgate"
  labels:
    {{- include "so-evening-tailgate.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/so-evening-tailgate"
  type: Opaque
{{- end }}
